services:
  db:
    image: postgres:16-alpine
    container_name: kinko_db
    restart: always
    environment:
      POSTGRES_USER: kinko_user
      POSTGRES_PASSWORD: kinko_super_secret_password # Cámbiala por una segura
      POSTGRES_DB: kinko
    ports:
      - "5432:5432" # Expone el puerto localmente para que puedas conectarte con DBeaver/Datagrip
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: kinko_backend
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg://kinko_user:kinko_super_secret_password@db:5432/kinko
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
    name: kinko_pg_data